module.exports = {
  style: 'elastic-web',
  name: 'crypto-trade-surveillance-demo',
  title: 'The market is a log source: trade surveillance on Elastic Security',
  repo: 'cojoe01/crypto-trade-surveillance-demo',            // powers slide comments (GitHub issues)
  gateway: 'https://api.fslides.dev',   // sign-in broker for commenting on the published deck
  slidesDir: 'slides',

  slides: [
    'cover.html',
    'insight.html',
    'premise.html',
    'roc.html',
    'objectives.html',
    'challenges.html',
    'datamodel.html',
    'coverage.html',
    'spoofing.html',
    'wash.html',
    'pump.html',
    'identity.html',
    'workflow.html',
    'ai.html',
    'proof.html',
    'closing.html',
  ],

  labels: [
    'Cover',
    'The insight',
    'The premise',
    'The setup',
    'Objectives',
    'Challenges',
    'Data model',
    'Coverage',
    'Spoofing',
    'Wash trading',
    'Pump and dump',
    'Fraud meets cyber',
    'Analyst workflow',
    'AI-assisted detections',
    'Proof point',
    'Thank you',
  ],
};
